INSERT INTO "Device" (id, name, description, location_id, parent_id) 
VALUES 
(1,'LCP','Klimatyzator międzyrzędowy Rittal',1, 1),
(2,'LCPPlusEC','Klimatyzator międzyrzędowy Rittal',1,1),
 (3,'EMDX3','Analizator sieci elek.',1,1),
 (4,'Sepam10','Przekaźnik zabezpieczeniowy',1,1),
 (5,'Sepam83','Przekaźnik zabezpieczeniowy',1,1),
 (6,'Diris_SN_v2','Tablicowy miernik energii',1,1),
 (7,'DirisA40','Tablicowy miernik energii',1,1),
 (8,'DMX3','Wyłącznik i rozłącznik powietrzny',1,1),
 (9,'DryCooler','Dry Cooler - sucha chłodnica cieczy',1,1),
 (10,'Turbocor','Chiller -Wytwornica wody lodowej',1,1),
 (11,'Grundfos','Pompa',1,1),
 (12,'Hydro','Pompa',1,1),
 (13,'HPM','Klimatyzator STULZ',1,1),
 (14,'generator','Generator prądotwórczy',1,1),
 (15,'hotcold','Termometr, higrometr, punkt rosy',1,1),
 (16,'ups_bst','UPS, tor zasilania A',1,1),
 (17,'STULZ','Klimatyzator STULZ',1,1),
 (18,'MGE','UPS, tor zasilania RU1',1,1),
 (19,'MGE_7000','UPS, tor zasilania RU2',1,1),
 (20,'Bender','System monitorowania prądów różnicowych',1,1),
 (21,'PM710','Tablicowy miernik energii',1,1),
 (22,'Masterys','UPS, tor zasilania RUPS',1,1),
 (23,'WIB_7000','Klimatyzatory STULZ',1,1),
 (24,'MeterDefinition','Licznik energii',1,1),
 (25,'MeterDefinition2','Licznik ciepła',1,1),
 (26,'Uzdat','Stacja uzdatniania wody',1,1),
 (27,'Fancoil','Klimakonwektor',1,1),
 (28,'UNIFLAIR','Chiller -Wytwornica wody lodowej',1,1),
 (29,'Astec','Licznik energii',1,1);